---
- name: Instalacao OFF
  hosts: IMPRESSAO
  become: false
  gather_facts: false
  remote_user: nomeDoUsuario

  tasks:
  - name: Criando pasta
    ansible.windows.win_powershell:
      script: |
        cd /
        mkdir "Drivers e Utilitarios"

  - name: Verificando arquivos necessarios e removendo lixo Setup
    ansible.windows.win_powershell:
      script: |
        Remove-Item -path 'C:\REMOVENDO DIRETORIO\' -recurse
           
  - name: Download SETUP
    ansible.windows.win_get_url:
      url: LINK HTTPS
      dest: C:\Drivers e Utilitarios\Setup.exe

  - name: Extraindo arquivos necessarios
    ansible.windows.win_package:
      path: C:\Drivers e Utilitarios\Setup.exe
      state: present 
        
  - name: Download 
    ansible.windows.win_get_url:
      url: LINK HTTPS
      dest: C:\Drivers e Utilitarios\Instalador.exe

  - name: Download
    ansible.windows.win_get_url:
      url: LINK HTTPS
      dest: C:\Drivers e Utilitarios\Install.exe

  - name: Instalando aplicativo
    ansible.windows.win_package:
      path: C:\Drivers e Utilitarios\Install.exe
      state: present

  - name: Download
    ansible.windows.win_get_url:
      url: LINK HTTPS
      dest: C:\Drivers e Utilitarios\Install.exe

  - name: Instalando aplicativo
    ansible.windows.win_package:
      path: C:\Drivers e Utilitarios\Install.exe
      state: present

  - name: Download MySql
    ansible.windows.win_get_url:
      url: LINK HTTPS
      dest: C:\Drivers e Utilitarios\Instalador_MySql5.exe

  - name: Instalando aplicativo MySql 5.1
    ansible.windows.win_package:
      path: C:\Drivers e Utilitarios\Instalador_MySql5.exe
      state: present

  - name: Download W
    ansible.windows.win_get_url:
      url: LINK HTTPS
      dest: C:\W.zip

  - name: extrair W
    ansible.windows.win_powershell:
      script: |
        Expand-Archive -Path C:\W.zip -DestinationPath C:\W

  - name: Download Fontes
    ansible.windows.win_get_url:
      url: LINK HTTPS
      dest: C:\Drivers e Utilitarios\Instalador_Fontes.exe

  - name: Instalando as Fontes
    ansible.windows.win_package:
      path: C:\Drivers e Utilitarios\Instalador_Fontes.exe
      state: present

  - name: Criando pasta dos instaladores de impressora
    ansible.windows.win_powershell:
      script: |
        cd /
        mkdir "Drivers e Utilitarios\Impressoras"    

  - name: Download drivers de impressora B
    ansible.windows.win_get_url:
      url: LINK HTTPS
      dest: C:\Drivers e Utilitarios\Impressoras\B.exe

  - name: Instalador Bematech
    ansible.windows.win_package:
      path: C:\Drivers e Utilitarios\Impressoras\B.exe
      state: present

  - name: Download drivers de impressora D
    ansible.windows.win_get_url:
      url: LINK HTTPS
      dest: C:\Drivers e Utilitarios\Impressoras\D.exe

  - name: Instalador Daruma
    ansible.windows.win_package:
      path: C:\Drivers e Utilitarios\Impressoras\D.exe
      state: present

  - name: Download drivers de impressora E
    ansible.windows.win_get_url:
      url: LINK HTTPS
      dest: C:\Drivers e Utilitarios\Impressoras\E.exe

  - name: Instalador Epson
    ansible.windows.win_package:
      path: C:\Drivers e Utilitarios\Impressoras\E.exe
      state: present

  - name: Download drivers de impressora E2
    ansible.windows.win_get_url:
      url: LINK HTTPS
      dest: C:\Drivers e Utilitarios\Impressoras\E2.exe

  - name: Instalador Elgin
    ansible.windows.win_package:
      path: C:\Drivers e Utilitarios\Impressoras\E2.exe
      state: present

  - name: Criando NOVA PASTA
    ansible.windows.win_powershell:
      script: |
        cd /
        mkdir "Drivers e Utilitarios\C" 

  - name: Download CHtools
    ansible.windows.win_get_url:
      url: LINK HTTPS
      dest: C:\Drivers e Utilitarios\CHtools\C.exe

  - name: Instalando CHtools
    ansible.windows.win_package:
      path: C:\Drivers e Utilitarios\Chtools\C.exe
      state: present

  - name: adicionando regras de firewall
    ansible.windows.win_powershell:
      script: |
        netsh advfirewall firewall add rule name= "Open Port 3000" dir=in action=allow protocol=TCP localport=3000

  - name: adicionando regras de firewall 3306
    ansible.windows.win_powershell:
      script: |
        netsh advfirewall firewall add rule name= "Open Port 3306" dir=in action=allow protocol=TCP localport=3306

  - name: registrando ODBC
    ansible.windows.win_powershell:
      script: |
        c:\windows\syswow64\odbcconf.exe configsysdsn "MySQL ODBC 5.1 Driver" "DSN=CHIANCA;SERVER=127.0.0.1;PORT=3306;DATABASE=CADASTROS;UID=root"

  - name: Instalando IIS (Web-Server and Web-Common-Http)
    ansible.windows.win_feature:
      name:
      - Web-Server
      - Web-Common-Http
      state: present

  - name: Install IIS Web-Server e include_management_tools
    ansible.windows.win_feature:
      name: Web-Server
      state: present
      include_sub_features: yes
      include_management_tools: yes
      register: win_feature

  - name: permissao na pasta
    ansible.windows.win_acl:
      user: everyone
      path: caminho da pasta
      reorganize: present
      type: present
      rights: ExecuteFile,Write

  - name: Compartilhando pasta
    ansible.windows.win_share:
      name: nome do compartilhamento
      description: descrição da pasta
      path: caminho da pasta
      list: yes
      full: everyone
      read: Global

  - name: Criando usuario 
    ansible.windows.win_user:
      name: USUARIO
      password: Senhausuario
      state: present
      user_cannot_change_password: yes
      password_never_expires: yes
      groups:
        - Administradores

  - name: Controle de acesso do usuário e as permissões
    ansible.windows.win_powershell:
      script: |
        /k %windir%\System32\reg.exe ADD HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System /v EnableLUA /t REG_DWORD /d 0 /f

  - name: Criando o IIS
    ansible.windows.win_powershell:
      script: |
        New-WebAppPool -name "WS_CHWeb" - force
        $appPool = Get-Item "IIS: caminho da pasta IIS"
        $appPool.processModel.identityType = "ApplicationPoolIdentity"
        $appPool.enable32BitAppOnWin64 = 0
        $appPool.managedRuntimeVersion = '4.0'
        $appPool.autoStart = 'true'

  - name: Adicionando permissao na pasta no Windows Defender
    ansible.windows.win_powershell:
      script: |
        Add-MpPreference -ExclusionPath caminho da pasta
        Add-MpPreference -ExclusionPath caminho da pasta

  - name: Download Plano de energia
    ansible.windows.win_get_url:
      url: LINK HTTPS
      dest: C:\Drivers e Utilitarios\Plano de energia\

  - name: Adicionando o plano de energia
    ansible.windows.win_powershell:
      script: |
        cd /
        cd C:\Drivers e Utilitarios\
        powercfg /import planoDeEnergia.pow

  - name: Alterando formato de data do windows
    ansible.windows.win_powershell:
      script: |
        get-date -uformat "%D / %y"

  - name: reiniciando o computador
    ansible.windows.win_reboot:
    when: res.reboot_required
